__name__ = "pillow_affine"
__description__ = "Affine transformation utilities for Pillow"
__version__ = "0.2.dev0"
__url__ = "https://github.com/pmeier/pillow_affine"
__license__ = "BSD 3-Clause"
__author__ = "Philip Meier"
__author_email__ = "github.pmeier@posteo.de"
